Repository upbound/up, pull requests merged in 2022-04, with the labels that each got.

#168 Add up Docker credential helper
  Makefile
  cmd/docker-credential-up/main.go
  cmd/up/controlplane.go
  cmd/up/login.go
  cmd/up/logout.go
  go.mod
  install.sh
  internal/build/build.go
  internal/config/config.go
  internal/config/mock_source.go
  internal/config/source.go
  internal/config/source_test.go
  internal/credhelper/credhelper.go
  internal/credhelper/credhelper_test.go
  nfpm_docker-credential-up.yaml
  nfpm_up.yaml
Labels: size/XL

#169 Clear token from config if logout successful
  cmd/up/logout.go
Labels: size/M

#171 Add credential chain fallback for docker-credential-up and `xpkg push`
  cmd/up/xpkg/push.go
Labels: size/S

#173 Add `docker-credential-up` information to README.md
  README.md
  docs/commands.md
Labels: size/M
