Repository upbound/up, pull requests merged in 2022-08, with the labels that each got.

#211 Do not prompt for username / password if token is provided
  cmd/up/login.go
Labels: size/XS, backport release-0.12

#217 Only pass domain to docker-credential-up
  cmd/docker-credential-up/main.go
Labels: size/S

#222 [Backport release-0.12] Embed Kubernetes client auth plugins
  cmd/up/main.go
  go.mod
  go.sum
Labels: size/XS

#221 Update comment about auth plugins
  cmd/up/main.go
Labels: size/XS

#224 Drop up uxp connect command
  cmd/up/uxp/connect.go
  cmd/up/uxp/uxp.go
  docs/commands.md
Labels: size/L

#225 Update MCP experimental ctp list with paging
  cmd/up/controlplane/list.go
  go.mod
  go.sum
Labels: size/S

#226 Move to pterm, emit success message for all operations, and support `--quiet` and `--pretty` global output config
  cmd/up/controlplane/controlplane.go
  cmd/up/controlplane/create.go
  cmd/up/controlplane/delete.go
  cmd/up/controlplane/kubeconfig/get.go
  cmd/up/controlplane/list.go
  cmd/up/license.go
  cmd/up/login.go
  cmd/up/login_test.go
  cmd/up/logout.go
  cmd/up/main.go
  cmd/up/uxp/install.go
  cmd/up/uxp/uninstall.go
  cmd/up/uxp/upgrade.go
  cmd/up/xpkg/build.go
  cmd/up/xpkg/dep.go
  cmd/up/xpkg/init.go
  cmd/up/xpkg/push.go
  cmd/up/xpkg/xpextract.go
  cmd/up/xpkg/xpextract_test.go
  go.mod
  go.sum
  internal/kube/client.go
Labels: size/L

#229 Add Nix installation instructions
  README.md
Labels: size/S

#230 Simplify `up upbound install` and add config command group
  Makefile
  cmd/up/controlplane/controlplane.go
  cmd/up/login.go
  cmd/up/main.go
  cmd/up/profile/config/config.go
  cmd/up/profile/config/set.go
  cmd/up/profile/config/set_test.go
  cmd/up/profile/config/unset.go
  cmd/up/profile/config/unset_test.go
  cmd/up/profile/current.go
  cmd/up/profile/list.go
  cmd/up/profile/profile.go
  cmd/up/profile/use.go
  cmd/up/profile/view.go
  cmd/up/upbound/connecting.go
  cmd/up/upbound/install.go
  cmd/up/upbound/profiles.go
  cmd/up/upbound/styles.go
  cmd/up/upbound/upgrade.go
  cmd/up/upbound/watchers.go
  go.mod
  go.sum
  internal/config/config.go
  internal/config/config_test.go
  internal/config/source.go
  internal/resources/deployment.go
  internal/resources/upbound.go
  internal/upbound/context.go
  internal/upbound/context_test.go
  internal/upbound/resolver.go
Labels: size/XXL

#231 Add support for organization management commands
  cmd/up/main.go
  cmd/up/organization/create.go
  cmd/up/organization/delete.go
  cmd/up/organization/list.go
  cmd/up/organization/organization.go
  go.mod
  go.sum
Labels: size/L

#234 Support robot management commands
  cmd/up/main.go
  cmd/up/robot/create.go
  cmd/up/robot/delete.go
  cmd/up/robot/list.go
  cmd/up/robot/robot.go
  cmd/up/robot/token/create.go
  cmd/up/robot/token/delete.go
  cmd/up/robot/token/list.go
  cmd/up/robot/token/token.go
  go.mod
  go.sum
Labels: size/XL

#238 Add --force option to destructive commands
  cmd/up/organization/delete.go
  cmd/up/repository/delete.go
  cmd/up/robot/delete.go
  cmd/up/robot/token/delete.go
  cmd/up/xpkg/init.go
  cmd/up/xpkg/init_test.go
  internal/input/prompt.go
Labels: size/L

#236 Move experimental and preview commands to `alpha` group
  cmd/up/controlplane/controlplane.go
  cmd/up/main.go
  cmd/up/robot/robot.go
  cmd/up/upbound/upbound.go
  cmd/up/xpkg/xpextract.go
  cmd/up/xpkg/xpextract_test.go
  cmd/up/xpkg/xpkg.go
  internal/upbound/context.go
Labels: size/M

#241 Fix up logout and hint when session is missing
  cmd/up/logout.go
  internal/config/config.go
  internal/upbound/context.go
  internal/upbound/context_test.go
Labels: size/M

#243 Update go-containerregistry to v0.11.0
  go.mod
  go.sum
  internal/xpkg/dep/manager/manager_test.go
  internal/xpkg/dep/marshaler/xpkg/marshaler_test.go
  internal/xpkg/layers.go
Labels: size/S

#245 Fix top-level alpha command help output and updates docs for v0.13.0 release
  cmd/up/main.go
  docs/commands.md
  docs/maturity.md
  docs/workflows.md
  internal/feature/maturity.go
Labels: size/XL

#246 Update configuration docs to include base config
  docs/configuration.md
Labels: size/M

#248 Set Go version to 1.18 in promote workflow
  .github/workflows/promote.yml
Labels: size/XS

#251 Use compact usage output
  cmd/up/main.go
Labels: size/XS
