Repository upbound/up, pull requests merged in 2022-02, with the labels that each got.

#145 Add support for validating XRD's openAPIV3Schema
  .github/workflows/ci.yml
  go.mod
  go.sum
  internal/vendor/README.md
  internal/vendor/github.com/crossplane/crossplane/controller/apiextensions/composite/api.go
  internal/vendor/github.com/crossplane/crossplane/controller/apiextensions/composite/placeholder.go
  internal/vendor/github.com/crossplane/crossplane/controller/apiextensions/composite/reconciler.go
  internal/vendor/github.com/crossplane/crossplane/controller/apiextensions/go.mod
  internal/vendor/github.com/crossplane/crossplane/xcrd/crd.go
  internal/vendor/github.com/crossplane/crossplane/xcrd/go.mod
  internal/vendor/github.com/crossplane/crossplane/xcrd/schemas.go
  internal/vendor/golang.org/x/tools/go.mod
  internal/xpkg/snapshot/composition.go
  internal/xpkg/snapshot/dne.go
  internal/xpkg/snapshot/meta.go
  internal/xpkg/snapshot/snapshot.go
  internal/xpkg/snapshot/validators.go
  internal/xpkg/snapshot/xrd.go
  internal/xpkg/snapshot/xrd_test.go
Labels: size/XL

#147 Update go-containerregistry to v0.8.0
  go.mod
  go.sum
  internal/install/helm/registry_test.go
Labels: size/XS

#148 Update opencontainers and containerd dependencies
  go.mod
  go.sum
Labels: size/XS

#149 Capture validators for XRD if schema def is broken
  internal/xpkg/snapshot/validators.go
Labels: size/S

#155 Add up enterprise mail command
  cmd/up/enterprise/enterprise.go
  cmd/up/enterprise/mail.go
  cmd/up/enterprise/mail_test.go
  cmd/up/enterprise/templates/mail.html
  internal/generate.go
Labels: size/L
