Repository upbound/up, pull requests merged in 2022-05, with the labels that each got.

#175 Update github.com/containerd/containerd to v1.5.10 for dependabot alert
  go.mod
  go.sum
Labels: size/XS

#177 Add example support to `xpkg build`
  Makefile
  cmd/docker-credential-up/main.go
  cmd/up/xpkg/build.go
  cmd/up/xpkg/push.go
  internal/credhelper/credhelper.go
  internal/xpkg/build.go
  internal/xpkg/build_test.go
  internal/xpkg/dep/marshaler/xpkg/marshaler.go
  internal/xpkg/dep/marshaler/xpkg/marshaler_test.go
  internal/xpkg/layers.go
  internal/xpkg/lint.go
  internal/xpkg/lint_test.go
  internal/xpkg/name.go
  internal/xpkg/parser/examples/parser.go
  internal/xpkg/parser/ndjson/parser.go
  internal/xpkg/parser/yaml/parser.go
  internal/xpkg/scheme/scheme.go
  internal/xpkg/scheme/scheme_test.go
  internal/xpkg/snapshot/composition_test.go
  internal/xpkg/snapshot/meta.go
  internal/xpkg/snapshot/snapshot.go
  internal/xpkg/testdata/config_meta.yaml
  internal/xpkg/testdata/config_package.yaml
  internal/xpkg/testdata/crossplane.yaml
  internal/xpkg/testdata/examples/ec2/instance.yaml
  internal/xpkg/testdata/examples/ec2/internetgateway.yaml
  internal/xpkg/testdata/examples/ecr/repository.yaml
  internal/xpkg/testdata/examples/provider.yaml
  internal/xpkg/testdata/package.ndjson
  internal/xpkg/testdata/package2.ndjson
  internal/xpkg/testdata/provider_meta.yaml
  internal/xpkg/testdata/provider_package.yaml
  internal/xpkg/testdata/providerconfigs.helm.crossplane.io.yaml
  internal/xpkg/testdata/providerconfigusages.helm.crossplane.io.yaml
  internal/xpkg/testdata/sha256:295bcd0e6dc396cf0f5ef638c8a7610a571ff2dcef3aa0447398f25b5a0eafc7
  internal/xpkg/workspace/meta/meta.go
  internal/xpkg/workspace/meta/meta_test.go
Labels: size/XL

#180 Supporting extracting contents from local xpkg
  cmd/up/xpkg/push.go
  cmd/up/xpkg/xpextract.go
  cmd/up/xpkg/xpextract_test.go
  cmd/up/xpkg/xpkg.go
Labels: size/M

#181 Replace `UP_ENDPOINT` with `UP_DOMAIN`
  cmd/docker-credential-up/main.go
  cmd/up/controlplane.go
  cmd/up/login.go
  cmd/up/login_test.go
  cmd/up/logout.go
  cmd/up/main.go
  cmd/up/xpkg/push.go
  internal/credhelper/credhelper.go
  internal/credhelper/credhelper_test.go
  internal/upbound/context.go
Labels: size/L
