Repository upbound/up, pull requests merged in 2022-07, with the labels that each got.

#193 Add support for pushing multiple xpkg and an index
  cmd/up/xpkg/push.go
  go.mod
Labels: size/L

#196 Update helm to v3.9.0 and k8s to v1.24
  go.mod
  go.sum
  internal/install/helm/helm.go
  internal/install/helm/restclientgetter.go
  internal/xpkg/snapshot/xrd.go
Labels: size/S

#197 Add support for experimental MCP API and drop control plane tokens
  cmd/up/controlplane.go
  cmd/up/controlplane/attach.go
  cmd/up/controlplane/create.go
  cmd/up/controlplane/delete.go
  cmd/up/controlplane/kubeconfig/get.go
  cmd/up/controlplane/list.go
  cmd/up/controlplane/token/create.go
  cmd/up/controlplane/token/delete.go
  cmd/up/controlplane/token/list.go
  cmd/up/controlplane/token/token.go
  go.mod
  go.sum
Labels: size/L

#198 Clean up commands doc after mcp experimental changes
  docs/commands.md
Labels: size/S

#194 Update `ctp kubeconfig get` default Proxy URL
  cmd/up/controlplane/kubeconfig/get.go
  internal/kube/client.go
Labels: size/M

#200 Construct proxy endpoint in up context
  cmd/up/controlplane/kubeconfig/get.go
  internal/upbound/context.go
Labels: size/M

#201 Include controlPlanes in proxy path
  cmd/up/controlplane/kubeconfig/get.go
Labels: size/XS

#204 Only add /k8s to kubeconfig server if experimental
  cmd/up/controlplane/kubeconfig/get.go
  internal/kube/client.go
Labels: size/S

#202 Migrate enterprise commands to upbound
  cmd/up/main.go
  cmd/up/upbound/install.go
  cmd/up/upbound/mail.go
  cmd/up/upbound/mail_test.go
  cmd/up/upbound/templates/mail.html
  cmd/up/upbound/uninstall.go
  cmd/up/upbound/upbound.go
  cmd/up/upbound/upgrade.go
Labels: size/L

#205 Update commands docs to reflect new upbound group
  docs/commands.md
Labels: size/M
