Repository upbound/up, pull requests merged in 2022-01, with the labels that each got.

#133 Add support for v1alpha1 Configuration and Provider types
  internal/xpkg/dep/manager/utils.go
  internal/xpkg/snapshot/deprecation_test.go
  internal/xpkg/snapshot/meta.go
  internal/xpkg/snapshot/snapshot.go
  internal/xpkg/snapshot/validator.go
  internal/xpkg/snapshot/validator/validator.go
  internal/xpkg/workspace/meta/meta.go
  internal/xpkg/workspace/meta/meta_test.go
Labels: size/XL

#134 Add showMessage support to `xpls` and new version notifications
  internal/version/version.go
  internal/version/version_test.go
  internal/xpls/server/server.go
Labels: size/L

#143 Remove stale reference to up cloud commands
  docs/configuration.md
Labels: size/S

#142 Validate `crossplane.yaml` as part of initialization
  internal/xpkg/snapshot/snapshot.go
  internal/xpkg/workspace/workspace.go
  internal/xpls/server/server.go
Labels: size/M
